### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by CheXinyu** [RedForestLonvor/PU-SignUpBot#11]
为什么南京工业大学选不了

**Comment by RedForestLonvor** [comment]
不清楚原因 这个可以联系另一位开发者
如果不行的话，建议使用之前的版本:
https://github.com/RedForestLonvor/PU-SignUpBot/tree/acd76d5b804a1b7c45297fa308ada47023249c43
在这个版本中没有提供学校选单，反而，需要用户手动输入sid

**Comment by CheXinyu** [comment]
我用另一位大佬的脚本，然后情况是搜不到南工大的sid，我真怀疑南工是野鸡大学了
![c333cb728800b0d8ce932bf8eb4c2da9](https://github.com/user-attachments/assets/5d28d33c-677b-4812-a579-4a52f5974e59)

![d37c1663588671d4766ce98f05d8ca3c](https://github.com/user-attachments/assets/6971ee01-dee3-49b7-b9b2-e847a8e2354d)

**Comment by RedForestLonvor** [comment]
如果是这样的话 按理说你在网页端正常登陆的时候也找不到你的学校呀

**Comment by CheXinyu** [comment]
网页登录是可以找到我们学校的

**Comment by RedForestLonvor** [comment]
奇怪哦 那你还是手动试一下uid吧
或者 我可能过几天处理一下？（也许（（（

**Comment by CheXinyu** [comment]
我们学校的端口不一样，是独立的，up不用管了
