### ISSUE TITLE
为啥不直接用账号密码登录

### ISSUE THREAD

**Issue by 861052359** [RedForestLonvor/PU-SignUpBot#5]
pu网页版有账号密码登录，直接用账号密码登录不可以吗？还有想请问一下，我这个报名的时候提示，访问人数过多，然后提示频繁操作，再就是提示，名额已满

**Comment by RedForestLonvor** [comment]
它的sid应该是在前端构造的。我没写，，
访问人数过多吗，那我也没啥办法了，，解决方法或许是重新卡一下它的timing

**Comment by RedForestLonvor** [comment]
最新的pr里sid的问题解决了
