### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by huayu0824** [RedForestLonvor/PU-SignUpBot#8]
我运行那个主程序显示没有这个模块呀大佬

**Comment by xiaonanbunan** [comment]
这个应该怎么用啊

**Comment by RedForestLonvor** [comment]
pip install requests

**Comment by RedForestLonvor** [comment]
对不起 我在考研 所以暂时没有时间添加一个requirements.txt
也暂时没有时间写一个详细的使用教程。

大约来说，你需要首先安装相关的运行环境（建议使用python3.9以上的版本，可以使用pip install 安装缺失的库（或许是pip3 install?）这里和你的python环境有关）

然后运行main.py 可以选择在ide里（比如pycharm/vscode）或者使用python main.py（python3 main.py）
然后应该就可以在提示下进行相关操作了。

不过我建议把这个程序部署在一个服务器上，用tmux之类的东西，不然你得一直保持程序运行 保持电脑有电...

**Comment by xiaonanbunan** [comment]
非常感谢，很抱歉再次打扰您，activity_ids.txt中id怎么更改，下载下来打开的activity_ids.txt中内容是空的

**Comment by xiaonanbunan** [comment]
在输入基本信息后运行显示活动id文件不存在

**Comment by huayu0824** [comment]
> pip 安装请求

大佬，我这样是不是就算成功了。
我开着机不动等到活动开始，就能自动报名了是吧

**Comment by RedForestLonvor** [comment]
我看不到你的图片（
但是你可以拿一个已经结束报名的活动试一下

**Comment by RedForestLonvor** [comment]
还有 你不是高中生吗为啥要用这个

**Comment by xiaonanbunan** [comment]
用户数据：
12023025025
是否新增用户 (y/n): n
线程：12023025025
登录失败: Token获取失败
登录失败: Token获取失败
登录失败: Token获取失败
登录失败: Token获取失败
登录失败: Token获取失败
无法获取有效的Token, 报名中止
 大佬这个怎么办

**Comment by RedForestLonvor** [comment]
登录失败了 就是这样（
这不是一个成熟的软件 所以你最好自己研究看看发生了什么
如果还是有问题或许可以问问另一位开发者 （也许？如果能联系到他
因为现在的好多代码是他写的

**Comment by huayu0824** [comment]
> 对不起 我在考研 所以暂时没有时间添加一个requirements.txt 也暂时没有时间写一个详细的使用教程。
> 
> 大约来说，你需要首先安装相关的运行环境（建议使用python3.9以上的版本，可以使用pip install 安装缺失的库（或许是pip3 install?）这里和你的python环境有关）
> 
> 然后运行main.py 可以选择在ide里（比如pycharm/vscode）或者使用python main.py（python3 main.py） 然后应该就可以在提示下进行相关操作了。
> 
> 不过我建议把这个程序部署在一个服务器上，用tmux之类的东西，不然你得一直保持程序运行 保持电脑有电...

哈哈我忘记改啦，现在是大一
