### ISSUE TITLE
关于多线程报名的一些问题

### ISSUE THREAD

**Issue by DGYJ-fufu** [RedForestLonvor/PU-SignUpBot#9]
我发现我在使用PU口袋这个报名接口时存在一个1.85s的请求间隔限制，我想问一下这个您是怎么处理的

**Comment by RedForestLonvor** [comment]
事实上关键在于卡第一次请求的timing
之后的请求只是亡羊补牢
所以简单的可以sleep

**Comment by DGYJ-fufu** [comment]
原来如此，感谢🙏
